src/main/events/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Acme Event</label>
    <nameField>
        <label>Acme Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acme Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/events/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/events/objects/Event__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique Id for this event</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/events/objects/EventRegistration__c/EventRegistration__c.object-meta.xml
<CustomObject>
    <description>An individual&apos;s registration record for an Event</description>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Event Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/events/objects/EventRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/IsNoShow__c.field-meta.xml
<CustomField>
    <fullName>IsNoShow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Show</label>
    <type>Checkbox</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Invited&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/test/core/classes/EventDomainTest.cls
@IsTest(IsParallel = true)
public class EventDomainTest {
    private static final String EVENT_UUID = 'event-uuid-123';
    private static final String EMAIL = 'dolly@dollyparton.com';
    private static final String EMAIL2 = 'david@attenboroughfilm.com';
    private static final String EMAIL3 = 'morgan.freeman@gmail.com';

    @TestSetup
    static void makeData() {
        Event__c event = new Event__c(
            Name = 'Test Event'
            , Uuid__c = EVENT_UUID
            , Status__c = EventRegistrationService.EVENT_STATUS_NEW
        );
        EventRegistration__c registration = new EventRegistration__c(
            FirstName__c = 'Dolly'
            , LastName__c = 'Parton'
            , Email__c = EMAIL
            , IsNoShow__c = false
            , Status__c = EventRegistrationService.REGISTRATION_STATUS_INVITED
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        EventRegistration__c registration2 = new EventRegistration__c(
            FirstName__c = 'David'
            , LastName__c = 'Attenborough'
            , Email__c = EMAIL2
            , IsNoShow__c = false
            , Status__c = EventRegistrationService.REGISTRATION_STATUS_INVITED
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        EventRegistration__c registration3 = new EventRegistration__c(
            FirstName__c = 'Morgan'
            , LastName__c = 'Freeman'
            , Email__c = EMAIL3
            , IsNoShow__c = false
            , Status__c = EventRegistrationService.REGISTRATION_STATUS_REGISTERED
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        insert new List<SObject> {event, registration, registration2, registration3};
    }

    @IsTest
    static void it_should_generate_uuid_when_null() {
        Event__c myEvent = [SELECT Id, Uuid__c FROM Event__c];
        System.assertNotEquals(null, myEvent.Uuid__c);

        myEvent = new Event__c(
            Id = myEvent.Id
            , Name = 'Test Event'
            , Uuid__c = null
        );

        EventDomain domain = new EventDomain(new List<Event__c> {myEvent}, null, null, TriggerOperation.BEFORE_INSERT);
        domain.execute();

        System.assertNotEquals(null, myEvent.Uuid__c);

        myEvent.Uuid__c = null;
        domain = new EventDomain(new List<Event__c> {myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, TriggerOperation.BEFORE_UPDATE);
        domain.execute();

        System.assertNotEquals(null, myEvent.Uuid__c);
    }

    @IsTest
    static void it_should_mark_invited_registrations_no_show_when_completed() {
        Event__c myEvent = [SELECT Id FROM Event__c];
        myEvent.Status__c = EventRegistrationService.EVENT_STATUS_COMPLETED;
        update myEvent;

        List<EventRegistration__c> results = [
            SELECT Id
            , IsNoShow__c
            FROM EventRegistration__c
            WHERE Status__c = :EventRegistrationService.REGISTRATION_STATUS_INVITED
        ];
        System.assertEquals(2, results.size());
        for (EventRegistration__c result : results) {
            System.assertEquals(true, result.IsNoShow__c);
        }
    }

    @IsTest
    static void it_should_not_mark_no_shows_when_event_already_completed() {
        Event__c myEvent = [SELECT Id FROM Event__c];
        myEvent.Status__c = EventRegistrationService.EVENT_STATUS_COMPLETED;

        EventDomain domain = new EventDomain(new List<Event__c> {myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, TriggerOperation.AFTER_UPDATE);
        domain.execute();

        List<EventRegistration__c> results = [
            SELECT Id
            , IsNoShow__c
            FROM EventRegistration__c
            WHERE Status__c = :EventRegistrationService.REGISTRATION_STATUS_INVITED
        ];
        System.assertEquals(2, results.size());
        for (EventRegistration__c result : results) {
            System.assertEquals(false, result.IsNoShow__c);
        }
    }
}