src/main/events/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Acme Event</label>
    <nameField>
        <label>Acme Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acme Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/events/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/events/objects/Event__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique Id for this event</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/events/objects/EventRegistration__c/EventRegistration__c.object-meta.xml
<CustomObject>
    <description>An individual&apos;s registration record for an Event</description>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Event Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/events/objects/EventRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Invited&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/events/classes/EventRegistrationService.cls
public with sharing class EventRegistrationService {
    public static final String EVENT_STATUS_NEW = 'New';
    public static final String EVENT_STATUS_OPEN = 'Open';
    public static final String EVENT_STATUS_CLOSED = 'Closed';
    public static final String EVENT_STATUS_COMPLETED = 'Completed';
    public static final String REGISTRATION_STATUS_INVITED = 'Invited';
    public static final String REGISTRATION_STATUS_REGISTERED = 'Registered';

    private WosSelector wosSelector {get; set;}

    private SObjectUnitOfWork uow {get; set;}

    public EventRegistrationService() {
        this.wosSelector = new WosSelector();
        this.uow = new SObjectUnitOfWork(new List<Schema.SObjectType> {
            EventRegistration__c.getSobjectType()
        });
    }

    public List<EventRegistration__c> fetchRegistrationsByEmail(String eventUuid, List<String> emails) {
        return fetchRegistrationsByEmail(new List<String> {eventUuid}, emails);
    }

    public List<EventRegistration__c> fetchRegistrationsByEmail(List<String> eventUuids, List<String> emails) {
        return this.wosSelector.fetchRegistrationsByEmail(eventUuids, emails);
    }

    public List<EventRegistration__c> fetchRegistrationsByStatusNotIn(List<Id> eventIds, List<String> statuses) {
        return this.wosSelector.fetchRegistrationsByStatusNotIn(eventIds, statuses);
    }

    public void updateRegistrations(List<EventRegistration__c> registrations, List<SObjectField> fieldsToUpdate) {
        this.uow.registerDirty(registrations, fieldsToUpdate);
        this.wosSelector.commitWork(this.uow);
    }

    private without sharing class WosSelector {
        private List<EventRegistration__c> fetchRegistrationsByEmail(List<String> eventUuids, List<String> emails) {
            return [
                SELECT Id
                , Name
                , Email__c
                , FirstName__c
                , LastName__c
                , Status__c
                , Event__r.Status__c
                , Event__r.Uuid__c
                FROM EventRegistration__c
                WHERE Event__r.Uuid__c IN : eventUuids
                AND Email__c IN : emails
            ];
        }

        private List<EventRegistration__c> fetchRegistrationsByStatusNotIn(List<Id> eventIds, List<String> statuses) {
            return [
                SELECT Id
                , Name
                , Email__c
                , FirstName__c
                , LastName__c
                , Status__c
                , Event__r.Status__c
                , Event__r.Uuid__c
                FROM EventRegistration__c
                WHERE Event__c IN : eventIds
                AND Status__c NOT IN : statuses
            ];
        }

        private void commitWork(SObjectUnitOfWork uow) {
            uow.commitWork();
        }
    }
}