src/main/events/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Acme Event</label>
    <nameField>
        <label>Acme Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acme Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/events/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/events/objects/Event__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique Id for this event</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/test/events/classes/EventDomainTest.cls
@IsTest(IsParallel = true)
public class EventDomainTest {
    private static final String EVENT_UUID = 'event-uuid-123';

    @TestSetup
    static void makeData() {
        Event__c event = new Event__c(
            Name = 'Test Event'
            , Uuid__c = EVENT_UUID
            , Status__c = EventRegistrationService.EVENT_STATUS_NEW
        );
        insert event;
    }

    @IsTest
    static void it_should_generate_uuid_when_null() {
        Event__c myEvent = [SELECT Id, Uuid__c FROM Event__c];
        System.assertNotEquals(null, myEvent.Uuid__c);

        myEvent = new Event__c(
            Id = myEvent.Id
            , Name = 'Test Event'
            , Uuid__c = null
        );

        EventDomain domain = new EventDomain(new List<Event__c> {myEvent}, null, null, TriggerOperation.BEFORE_INSERT);
        domain.execute();

        System.assertNotEquals(null, myEvent.Uuid__c);

        myEvent.Uuid__c = null;
        domain = new EventDomain(new List<Event__c> {myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, TriggerOperation.BEFORE_UPDATE);
        domain.execute();

        System.assertNotEquals(null, myEvent.Uuid__c);
    }

    @IsTest
    static void it_should_mark_invited_registrations_no_show_when_completed() {
        // setup - create a stub for service class
        UniversalMocker stubSvc = UniversalMocker.mock(EventRegistrationService.class);
        DependencyBuilder.cacheInstance(EventRegistrationService.class, stubSvc.createStub());

        // when
        Event__c myEvent = [SELECT Id FROM Event__c];
        myEvent.Status__c = EventRegistrationService.EVENT_STATUS_COMPLETED;
        update myEvent;

        // then
        stubSvc.assertThat().method('markUnregisteredAttendeesNoShow').wasCalledExactly(1);
        List<Id> eventIds = (List<Id>)stubSvc.forMethod('markUnregisteredAttendeesNoShow').getValueOf('eventids');
        System.assertEquals(new List<Id> {myEvent.Id}, eventIds);
    }

    @IsTest
    static void it_should_not_mark_no_shows_when_event_already_completed() {
        // setup - create a stub for service class
        UniversalMocker stubSvc = UniversalMocker.mock(EventRegistrationService.class);
        DependencyBuilder.cacheInstance(EventRegistrationService.class, stubSvc.createStub());

        Event__c myEvent = [SELECT Id FROM Event__c];
        myEvent.Status__c = EventRegistrationService.EVENT_STATUS_COMPLETED;

        EventDomain domain = new EventDomain(new List<Event__c> {myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, new Map<Id, Event__c> {myEvent.Id => myEvent}, TriggerOperation.AFTER_UPDATE);
        domain.execute();

        // then
        stubSvc.assertThat().method('markUnregisteredAttendeesNoShow').wasNeverCalled();
    }
}