src/main/events/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Acme Event</label>
    <nameField>
        <label>Acme Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Acme Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/events/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/main/events/objects/Event__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>Unique Id for this event</description>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/main/events/objects/EventRegistration__c/EventRegistration__c.object-meta.xml
<CustomObject>
    <description>An individual&apos;s registration record for an Event</description>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Event Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/events/objects/EventRegistration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/IsNoShow__c.field-meta.xml
<CustomField>
    <fullName>IsNoShow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Show</label>
    <type>Checkbox</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <complianceGroup>PII;GDPR;CCPA</complianceGroup>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/main/events/objects/EventRegistration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Invited&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/test/api/classes/EventRegistrationServiceTest.cls
@IsTest
public class EventRegistrationServiceTest {
    private static final String EVENT_UUID = 'event-uuid-123';
    private static final String EMAIL = 'dolly@dollyparton.com';
    private static final String EMAIL2 = 'david@attenboroughfilm.com';
    private static final String EMAIL3 = 'morgan.freeman@gmail.com';

    @TestSetup
    static void makeData() {
        Event__c event = new Event__c(
            Uuid__c = EVENT_UUID
            , Status__c = EventRegistrationService.EVENT_STATUS_OPEN
        );
        EventRegistration__c registration = new EventRegistration__c(
            FirstName__c = 'Dolly'
            , LastName__c = 'Parton'
            , Email__c = EMAIL
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        EventRegistration__c registration2 = new EventRegistration__c(
            FirstName__c = 'David'
            , LastName__c = 'Attenborough'
            , Email__c = EMAIL2
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        EventRegistration__c registration3 = new EventRegistration__c(
            FirstName__c = 'Morgan'
            , LastName__c = 'Freeman'
            , Email__c = EMAIL3
            , Event__r = new Event__c(Uuid__c = EVENT_UUID)
        );
        insert new List<SObject> {event, registration, registration2, registration3};
    }

    @IsTest
    static void fetchRegistrationsByEmail_should_fetch_event_registrations_by_email() {
        EventRegistrationService svc = new EventRegistrationService();
        List<String> emails = new List<String> {EMAIL, EMAIL2};
        List<EventRegistration__c> results = svc.fetchRegistrationsByEmail(EVENT_UUID, emails);
        System.assertEquals(2, results.size());
        // List<String> resultEmails = (List<String>)SListApi.fromList(results).pluck('Email__c').toList(new List<String>());
        List<String> resultEmails = new List<String>();
        for (EventRegistration__c result : results) {
            resultEmails.add(result.Email__c);
        }
        emails.sort();
        resultEmails.sort();
        System.assertEquals(emails, resultEmails, resultEmails);

        System.assertNotEquals(null, results[0].Id);
        System.assertNotEquals(null, results[0].Name);
        System.assertNotEquals(null, results[0].Email__c);
        System.assertNotEquals(null, results[0].FirstName__c);
        System.assertNotEquals(null, results[0].LastName__c);
        System.assertNotEquals(null, results[0].Status__c);
        System.assertNotEquals(null, results[0].Event__r.Status__c);
        System.assertNotEquals(null, results[0].Event__r.Uuid__c);
    }

    @IsTest
    static void updateRegistrations_should_update_registrations() {
        List<EventRegistration__c> registrations = [SELECT Id FROM EventRegistration__c];
        for (EventRegistration__c registration : registrations) {
            registration.FirstName__c = 'Connie';
            registration.LastName__c = 'Chung';
            registration.Status__c = 'Invited';
            registration.IsNoShow__c = true;
        }
        EventRegistrationService svc = new EventRegistrationService();
        svc.updateRegistrations(registrations, new List<SObjectField>());
        List<EventRegistration__c> results = [
            SELECT Id
            , FirstName__c
            , LastName__c
            , Status__c
            , IsNoShow__c
            FROM EventRegistration__c
        ];
        for (EventRegistration__c result : results) {
            System.assertEquals('Connie', result.FirstName__c);
            System.assertEquals('Chung', result.LastName__c);
            System.assertEquals('Invited', result.Status__c);
            System.assertEquals(true, result.IsNoShow__c);
        }
    }
}